### ISSUE TITLE
Not a issue, just an Appreciation

### ISSUE THREAD

**Issue by Thammachart** [markbirbeck/mydesktop#1]
Finally, I found someone who think Docker can be more than just a _worker_

---

This is my [repository](https://github.com/Thammachart/docker-shell-tooling) created around late 2016, only UNIX-based OSes supported

Both of our repos is based on the same basic concept, Docker used as a tooling for development plus the isolated environment that don't tamper with the host's one, and reusable when switching hardwares

The difference is mine using only Docker +  plain-old shell scripts, that is only limited to Docker for Mac, and Docker Engine in Linux, thus UNIX-based only

Your looks more sophisticated in term of using `docker-compose` to be more compatible for more underlying systems, and `npm` for easier installation

Thank you for your great idea!

---
P.S. Sorry for my inappropriate way to communicate. I don't how to contact you directly, so github issue is the only way.

**Comment by markbirbeck** [comment]
Thanks for your comments, and great to see what you doing in 2016. If you start porting any of your scripts to use the NPM approach I'd love to hear about it! It would be great to share solutions.

I recently created the corresponding configs for Bitlbee and Weechat, but now I'm just trying to work out how you might wire the two together. It's easy with Docker Compose, but not so easy to work out how to do it in such a way that it's pluggable (e.g., using a different IRC client, but still connecting to Bitlbee).

Anyway, thanks again for your comments, and keep me posted!
